### ISSUE TITLE
Can you specify which jar files is to be added

### ISSUE THREAD

**Issue by priyankashinolikar** [pranavkhurana/Time-table-scheduler#5]
After running the project this error is thrown by compiler.

Nostgrp=0 Noteachers=0 daysperweek=0 hoursperday=0
----Slots----
----------Initial Generation-----------

Fetching details from this generation...

Chromosome no.0: NaN

Chromosome no.1: NaN

Chromosome no.2: NaN

Chromosome no.3: NaN

Chromosome no. 101 :NaN

Chromosome no. 201 :NaN

Most fit chromosome from this generation has fitness = NaN

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at scheduler.SchedulerMain.selectParentRoulette(SchedulerMain.java:126)
	at scheduler.SchedulerMain.createNewGenerations(SchedulerMain.java:68)
	at scheduler.SchedulerMain.<init>(SchedulerMain.java:38)
	at scheduler.SchedulerMain.main(SchedulerMain.java:244)

**Comment by pranavkhurana** [comment]
Hey!
You can find the jar files that I used inside: WebContent/WEB-INF/lib/
Although it is not a standard practice to include jar files in the project directories, I've done that because I didn't use any dependency manager (like maven or gradle) at that time.
Also, of all the jar files present there, some were never used, but including them all should set you on track for once.

PS: remember to give location of the input.txt (if you are using it for giving inputs). Refer the steps I've given in the readme doc of the project.

**Comment by noahire** [comment]
Hi, 
I i have added all the file but the Exception is still coming up, Kindly help with this..
Nostgrp=0 Noteachers=0 daysperweek=0 hoursperday=0
----Slots----
----------Initial Generation-----------

Fetching details from this generation...

Chromosome no.0: NaN

Chromosome no.1: NaN

Chromosome no.2: NaN

Chromosome no.3: NaN

Chromosome no. 101 :NaN

Chromosome no. 201 :NaN

Most fit chromosome from this generation has fitness = NaN

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at scheduler.SchedulerMain.selectParentRoulette(SchedulerMain.java:126)
	at scheduler.SchedulerMain.createNewGenerations(SchedulerMain.java:68)
	at scheduler.SchedulerMain.<init>(SchedulerMain.java:38)
	at scheduler.SchedulerMain.main(SchedulerMain.java:244)
C:\Users\Noah\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 2 seconds)
