### ISSUE TITLE
Trouble With Inputdata.java

### ISSUE THREAD

**Issue by noahire** [pranavkhurana/Time-table-scheduler#6]
Hi,
I i have added all the file but the Exception is still coming up, Kindly help with this..
I think the Inputdata has a problem somewhere, because you gave daysperweeek and hoursperday initial value and yet they return 0.
Nostgrp=0 Noteachers=0 daysperweek=0 hoursperday=0
----Slots----
----------Initial Generation-----------

Fetching details from this generation...

Chromosome no.0: NaN

Chromosome no.1: NaN

Chromosome no.2: NaN

Chromosome no.3: NaN

Chromosome no. 101 :NaN

Chromosome no. 201 :NaN

Most fit chromosome from this generation has fitness = NaN

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.ArrayList.elementData(ArrayList.java:418)
at java.util.ArrayList.get(ArrayList.java:431)
at scheduler.SchedulerMain.selectParentRoulette(SchedulerMain.java:126)
at scheduler.SchedulerMain.createNewGenerations(SchedulerMain.java:68)
at scheduler.SchedulerMain.(SchedulerMain.java:38)
at scheduler.SchedulerMain.main(SchedulerMain.java:244)
C:\Users\Noah\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 2 seconds)

**Comment by a-anand-91119** [comment]
First set the input path of file in InputData class.

modify the main method of SchedulerMain as below
`public static void main(String[] args) {
		inputdata id = new inputdata();
		id.takeinput();
		new SchedulerMain();
	}`

Then run the SchedulerMain

**Comment by Kailashdash** [comment]
First set the input path of file in InputData class. --- I did'nt understand this line.
and after changing the Schdulermain class I am still getting error as inputdata class not found exception.
